aplicacion_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('apps.usuario.urls')),
    path('blog/', include('apps.blog.urls'))
]

apps/blog/urls.py
from django.urls import path
from .views import ListBlogsView, ListAllBlogsView, DetailBlogView, CreateBlogView, UpdateBlogView, DeleteBlogView, CreateFavoritosView, ListFavoritosView, reportBlog, reportListBlog, DeleteReportView, ListBuscarBlogsView, DeleteFavoritoView

# Create your urls here.


app_name = 'blogs'

urlpatterns = [
    path('', ListBlogsView.as_view(), name='list_blogs'),
    path('all_blogs/', ListAllBlogsView.as_view(), name='list_all_blogs'),
    path('create/', CreateBlogView.as_view(), name='create_blog'),
    path('<int:pk>/<slug:blog_slug>/', DetailBlogView.as_view(), name='read_blog'),
    path('update/<int:pk>/<slug:blog_slug>/', UpdateBlogView.as_view(), name='update_blog'),
    path('delete/<int:pk>/<slug:blog_slug>/', DeleteBlogView.as_view(), name='delete_blog'),
    path('create_favoritos/<int:blog_id>/', CreateFavoritosView, name='create_favoritos'),
    path('favoritos/', ListFavoritosView.as_view(), name='list_favoritos'),
    path('delete/Report/<int:pk>/<slug:blog_slug>/', DeleteReportView.as_view(), name='delete_blog_reporter'),
    path('report/<int:blogId>/', reportBlog , name='report_blog'),
    path('reportList/', reportListBlog , name='report_list_blogs'),
    path('buscar_blogs/', ListBuscarBlogsView.as_view() , name='buscar_blogs'),
    path('eliminar_favorito/<int:id_blog>/', DeleteFavoritoView , name='eliminar_favorito'),
]

apps/usuario/urls.py
from django.urls import path
from .views import SignUpView, UserDetailView, UserEditView, userDelete, SeguirUsuarioView, VerSiguiendoView, VerSeguidoresView, DeleteSeguidorView

# Create your urls here.
 

app_name = 'usuario'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', UserEditView.as_view(), name='edit_profile'),
    path('userDelete/<int:userId>/', userDelete , name='userDelete'),
    path('seguir_usuario/<int:user_id>/', SeguirUsuarioView , name='seguir_usuario'),
    path('ver_siguiendo/', VerSiguiendoView.as_view() , name='ver_siguiendo'),
    path('ver_seguidores/', VerSeguidoresView.as_view() , name='ver_seguidores'),
    path('dejar_seguir/<int:id_seguido>', DeleteSeguidorView , name='dejar_seguir'),
]

apps/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from apps.usuario.models import User

# Create your models here.


class Blog(models.Model):
    titulo = models.CharField(verbose_name="Título", max_length=200)
    contenido = RichTextField(verbose_name="Contenido")
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    fecha_actualizacion = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    reportada = models.BooleanField(default=False)

    def __str__(self):
        return self.titulo


class Favoritos(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    pagina = models.ForeignKey(Blog, on_delete=models.CASCADE) 

apps/blog/forms.py
from django import forms
from .models import Blog

# Create your forms here.


class BlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ['titulo', 'contenido']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Titulo'}), 
            'contenido': forms.TextInput(attrs={'class': 'form-control'}), 
        }

apps/blog/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Blog, Favoritos
from ..usuario.models import User, Seguidores
from .forms import BlogForm
from django.shortcuts import render

# Create your views here.


class ListBlogsView(ListView):
    model = Blog
    template_name = 'blog/blogs.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        return Blog.objects.filter(usuario=self.request.user)


class ListAllBlogsView(ListView):
    model = Blog
    template_name = 'blog/blogs_all.html'
    context_object_name = 'blogs'

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_anonymous:
            self.extra_context = { "all_favoritos": self.obtener_ids_favoritos(Favoritos.objects.filter(usuario=self.request.user)),
                                   "all_seguidos": self.obtener_ids_seguidos(Seguidores.objects.filter(seguidor=self.request.user))}
            print(self.extra_context)
        return super().get(request, *args, **kwargs)

    def obtener_ids_favoritos(self, lista_favoritos):
        lista_ids = []
        for favorito in lista_favoritos:
            lista_ids.append(favorito.pagina.id)
        return lista_ids

    def obtener_ids_seguidos(self, lista_seguidos):
        lista_ids = []
        for seguido in lista_seguidos:
            lista_ids.append(seguido.usuario_seguido.id)
        return lista_ids



class CreateBlogView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blogs:list_blogs')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        messages.success(self.request, 'Blog creado satisfactoriamente.')
        return super(CreateBlogView, self).form_valid(form)


class DetailBlogView(DetailView):
    model = Blog
    template_name = 'blog/blog.html'


class UpdateBlogView(UpdateView):
    model = Blog
    form_class = BlogForm
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('blogs:list_blogs')

    def get_success_url(self):
        messages.success(self.request, 'Blog actualizado satisfactoriamente.')
        return super().get_success_url()


class DeleteBlogView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:list_blogs')

    def get_success_url(self):
        messages.success(self.request, 'Blog eliminado satisfactoriamente.')
        return super().get_success_url()


def CreateFavoritosView(request, blog_id):
    usuario = User.objects.get(pk=request.user.id)
    blog = Blog.objects.get(pk=blog_id)
    nuevo_favorito = Favoritos(usuario=usuario, pagina=blog)
    nuevo_favorito.save()
    messages.success(request, f'Agregaste el blog {blog.titulo} a tus favoritos.')
    return HttpResponseRedirect(reverse('blogs:list_all_blogs'))


class ListFavoritosView(ListView):
    model = Favoritos
    template_name = 'blog/favoritos.html'
    context_object_name = 'favoritos'

    def get_queryset(self):
        return self.model.objects.filter(usuario=self.request.user)


class DeleteReportView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:report_list_blogs')

    def get_success_url(self):
        messages.success(self.request, 'Blog eliminado satisfactoriamente.')
        return super().get_success_url()

def reportBlog(request, blogId):
    blogReport = Blog.objects.get(id=blogId)
    blogReport.reportada = True
    blogReport.save()
    messages.success(request, 'Blog reportado satisfactoriamente')
    return HttpResponseRedirect(reverse('blogs:list_all_blogs'))

def reportListBlog(request):
    blogsReport = Blog.objects.filter(reportada=True)
    return render(request, 'blog_list_report.html', {"blogsReport": blogsReport})


class ListBuscarBlogsView(ListView):
    model = Blog
    template_name = 'blog/blogs_all.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        texto_busqueda = self.request.GET.get('texto_busqueda')
        return self.model.objects.filter(titulo__icontains=texto_busqueda)

    def get(self, request, *args, **kwargs):
        if self.request.user != "AnonymousUser":
            self.extra_context = { "all_favoritos": self.obtener_ids_favoritos(Favoritos.objects.filter(usuario=self.request.user)),
                                   "all_seguidos": self.obtener_ids_seguidos(Seguidores.objects.filter(seguidor=self.request.user))}
            print(self.extra_context)
        print(self.request.user)
        return super().get(request, *args, **kwargs)

    def obtener_ids_favoritos(self, lista_favoritos):
        lista_ids = []
        for favorito in lista_favoritos:
            lista_ids.append(favorito.pagina.id)
        return lista_ids

    def obtener_ids_seguidos(self, lista_seguidos):
        lista_ids = []
        for seguido in lista_seguidos:
            lista_ids.append(seguido.usuario_seguido.id)
        return lista_ids

def DeleteFavoritoView(request, id_blog):
    blog = Blog.objects.get(id=id_blog)
    user = User.objects.get(id=request.user.id)
    favorito = Favoritos.objects.get(pagina=blog, usuario=user)
    favorito.delete()
    messages.success(request, f'Eliminaste el blog {blog.titulo} de tus favoritos.')
    return HttpResponseRedirect(reverse('blogs:list_all_blogs'))

apps/blog/templates/blog/blog.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{blog.titulo}}{% endblock %}

{% block content %}

<main>
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-3">{{blog.titulo}}</h1>
            <div>
                {{blog.contenido|safe}}
            </div>
            <hr class="my-4">
            <p>Por {{ blog.usuario.username }}</p>
            <p>
                <a class="btn btn-primary btn-lg" role="button" href="{% url 'blogs:update_blog' blog.id blog.titulo|slugify %}"><i class="fas fa-edit"></i> Editar</a>
            </p>
        </div>
    </div>
</main>

{% endblock %}

apps/blog/templates/blog/blog_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{blog.titulo}}{% endblock %}

{% block content %}

<main role="main">
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-9 mx-auto">
                <div>
                    <form method="post">{% csrf_token %}
                        <p class="text-center">¿Está seguro de eliminar el blog "{{ blog.titulo }}"?</p>
                        <input type="submit" class="btn btn-primary btn-block" value="Confirm">
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

apps/blog/templates/blog/blog_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear blog{% endblock %}

{% block content %}

{% include 'blog/includes/ckeditor_config.html'%}

<style>
    label {
        display: none
    }
</style>

<main role="main">
    <div class="container">
        <div class="row mt-3 mb-5">
            <div class="col-md-9 mx-auto">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center">
                        <input type="submit" class="btn btn-primary btn-block" value="Crear blog" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

apps/blog/templates/blog/blog_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Editar blog{% endblock %}

{% block content %}

{% include 'blog/includes/ckeditor_config.html'%}

<main role="main">
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-9 mx-auto">
                <div>
                    {% if 'ok' in request.GET %}
                    <p style="color: green">
                        Se ha editado correctamente.
                        <a href="{% url 'blogs:read_blog' blog.id blog.titulo|slugify %}"> Ver los cambios</a>
                    </p>
                    {% endif %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <input type="submit" class="btn btn-primary btn-block" value="Editar blog" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

apps/blog/templates/blog/blogs.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Blogs{% endblock %}

{% block content %}

<main role="main">
    <div class="container mb-4">
        {% for blog in blogs %}
        <div class="container">
            <div class="jumbotron">
                <h1 class="display-3">{{blog.titulo}}</h1>
                <p class="lead">{{blog.contenido|striptags|safe|truncatechars:"200"}}</p>
                <hr class="my-4">
                <p class="lead">
                    <a class="btn btn-info btn-lg" role="button" href="{% url 'blogs:read_blog' blog.id blog.titulo|slugify %}"><i class="fab fa-readme"></i> Leer más</a>
                    <a class="btn btn-primary btn-lg" role="button" href="{% url 'blogs:update_blog' blog.id blog.titulo|slugify %}"><i class="fas fa-edit"></i> Editar</a>
                    <a class="btn btn-danger btn-lg" role="button" href="{% url 'blogs:delete_blog' blog.id blog.titulo|slugify %}"><i class="fas fa-trash-alt"></i> Borrar</a>
                </p>
            </div>
        </div>
        {% endfor %}
        <a class="btn btn-success btn-lg" role="button" href="{% url 'blogs:create_blog' %}"><i class="fas fa-plus"></i> Crear blog</a>
    </div>
</main>

{% endblock %}

apps/blog/templates/blog/blogs_all.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Blogs{% endblock %}

{% block content %}

<main role="main">
    <div class="container mb-4">

        {% if not blogs %}
        <div class="container col-md-10">
            <div style="padding-top:50px; text-align:center;">
                <h1>No existen blogs.</h1>
            </div>
        </div>
        {% endif %}

        {% for blog in blogs %}
        {% if not blog.reportada %}
        <div class="container">
            <div class="jumbotron">
                <h1 class="display-3">{{blog.titulo}}</h1>
                <p class="lead">{{blog.contenido|striptags|safe|truncatechars:"200"}}</p>
                <hr class="my-4">
                <p>Por {{ blog.usuario.username }}
                    {% if request.user.is_authenticated%}
                    {% if blog.usuario.id in all_seguidos%}
                    <a class="btn btn-outline-success btn-sm" role="button"
                        href="{% url 'usuario:dejar_seguir' blog.usuario.id %}"><i class="fas fa-user-plus"></i>
                        Dejar de seguir</a>
                        {% else %}
                        <a class="btn btn-outline-success btn-sm" role="button"
                        href="{% url 'usuario:seguir_usuario' blog.usuario.id %}"><i class="fas fa-user-plus"></i>
                        Seguir</a>
                    {% endif %}
                    {% endif %}
                </p>
                <p class="lead">
                    <a class="btn btn-info btn-lg" role="button"
                        href="{% url 'blogs:read_blog' blog.id blog.titulo|slugify %}"><i class="fab fa-readme"></i>
                        Leer más</a>
                    {% if request.user.is_authenticated %}
                    {% if blog.id in all_favoritos %}
                    <a class="btn btn-warning btn-lg" role="button" href="{% url 'blogs:eliminar_favorito' blog.id %}"><i
                            class="fas fa-heart-broken"></i> Eliminar de mis
                        favoritos</a>
                    {% else %}
                    <a class="btn btn-secondary btn-lg" role="button"
                        href="{% url 'blogs:create_favoritos' blog.id %}"><i class="fas fa-heart"></i> Agregar a mis
                        favoritos</a>
                    {% endif %}
                    <a class="btn btn-warning btn-lg" role="button" href="{% url 'blogs:report_blog' blog.id  %}"
                        class="link-danger" onclick="return confirm('Esta seguro en reportar {{ blog.titulo}}?')"><i
                            class="fas fa-bug"></i> Reportar</a>
                    {% if request.user.is_staff %}
                    <a class="btn btn-primary btn-lg" role="button"
                        href="{% url 'blogs:update_blog' blog.id blog.titulo|slugify %}"><i class="fas fa-edit"></i>
                        Editar</a>
                    {% endif %}
                    {% endif %}
                </p>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</main>

<script src="{% static 'blog/js/peticiones.js' %}"></script>

{% endblock %}

apps/blog/templates/blog/favoritos.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Tus favoritos{% endblock %}

{% block content %}

<main role="main">
    <div class="container mb-4">
        {% if  favoritos %}
        {% for favorito in favoritos %}
        <div class="container">
            <div class="jumbotron">
                <h1 class="display-3">{{favorito.pagina.titulo}}</h1>
                <p class="lead">{{favorito.pagina.contenido|striptags|safe|truncatechars:"200"}}</p>
                <hr class="my-4">
                <p class="lead">
                    <p>Por {{ favorito.pagina.usuario.username }}
                        <a class="btn btn-outline-success btn-sm" role="button" href="{% url 'usuario:seguir_usuario' favorito.pagina.usuario.id %}"><i class="fas fa-user-plus"></i> Seguir</a>
                    </p>
                    <p>
                        <a class="btn btn-info btn-lg" role="button" href="{% url 'blogs:read_blog' favorito.id favorito.pagina.titulo|slugify %}"><i class="fab fa-readme"></i>  Leer más</a>
                        <a class="btn btn-warning btn-lg" role="button" href="{% url 'blogs:eliminar_favorito' favorito.pagina_id %}"><i class="fas fa-heart-broken"></i> Eliminar de favoritos</a>
                    </p>
                </p>
            </div>
        </div>
        {% endfor %}
        {% else %}
            <h1>No Tienes ningun blog marcado como favorito.</h1>
        {% endif %}
    </div>
</main>

{% endblock %}