aplicacion_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('apps.usuario.urls')),
    path('blog/', include('apps.blog.urls'))
]

apps/blog/urls.py
from django.urls import path
from .views import ListBlogsView, ListAllBlogsView, DetailBlogView, CreateBlogView, UpdateBlogView, DeleteBlogView, CreateFavoritosView, ListFavoritosView, reportBlog, reportListBlog, DeleteReportView, ListBuscarBlogsView, DeleteFavoritoView

# Create your urls here.


app_name = 'blogs'

urlpatterns = [
    path('', ListBlogsView.as_view(), name='list_blogs'),
    path('all_blogs/', ListAllBlogsView.as_view(), name='list_all_blogs'),
    path('create/', CreateBlogView.as_view(), name='create_blog'),
    path('<int:pk>/<slug:blog_slug>/', DetailBlogView.as_view(), name='read_blog'),
    path('update/<int:pk>/<slug:blog_slug>/', UpdateBlogView.as_view(), name='update_blog'),
    path('delete/<int:pk>/<slug:blog_slug>/', DeleteBlogView.as_view(), name='delete_blog'),
    path('create_favoritos/<int:blog_id>/', CreateFavoritosView, name='create_favoritos'),
    path('favoritos/', ListFavoritosView.as_view(), name='list_favoritos'),
    path('delete/Report/<int:pk>/<slug:blog_slug>/', DeleteReportView.as_view(), name='delete_blog_reporter'),
    path('report/<int:blogId>/', reportBlog , name='report_blog'),
    path('reportList/', reportListBlog , name='report_list_blogs'),
    path('buscar_blogs/', ListBuscarBlogsView.as_view() , name='buscar_blogs'),
    path('eliminar_favorito/<int:id_blog>/', DeleteFavoritoView , name='eliminar_favorito'),
]

apps/core/urls.py
from django.urls import path
from .views import HomePageView

# Create your urls here.


app_name = 'core'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

apps/usuario/urls.py
from django.urls import path
from .views import SignUpView, UserDetailView, UserEditView, userDelete, SeguirUsuarioView, VerSiguiendoView, VerSeguidoresView, DeleteSeguidorView

# Create your urls here.
 

app_name = 'usuario'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', UserEditView.as_view(), name='edit_profile'),
    path('userDelete/<int:userId>/', userDelete , name='userDelete'),
    path('seguir_usuario/<int:user_id>/', SeguirUsuarioView , name='seguir_usuario'),
    path('ver_siguiendo/', VerSiguiendoView.as_view() , name='ver_siguiendo'),
    path('ver_seguidores/', VerSeguidoresView.as_view() , name='ver_seguidores'),
    path('dejar_seguir/<int:id_seguido>', DeleteSeguidorView , name='dejar_seguir'),
]

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.


class HomePageView(TemplateView):
    template_name = 'core/home.html'

apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="icon" type="image/jpg" href="{% static '/core/media/icon.png' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'blogs:list_all_blogs' %}">Blog app</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:list_all_blogs' %}"><i class="fab fa-blogger"></i> logs</a>
                </li>
                {% if request.user.is_authenticated %} 
                {% if request.user.is_staff %}
                <li> <a class="nav-link" href="{% url 'blogs:report_list_blogs'%}"> <i class="fas fa-bug"></i>  Reportes</a> </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                        aria-haspopup="true" aria-expanded="false">{{ request.user.username }}</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'usuario:profile' %}"><i class="far fa-user"></i> Mi perfil</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'blogs:list_blogs' %}">Mis blogs</a>
                        <a class="dropdown-item" href="{% url 'blogs:list_favoritos' %}">Mis favoritos</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'usuario:ver_seguidores' %}">Mis seguidores</a>
                        <a class="dropdown-item" href="{% url 'usuario:ver_siguiendo' %}">Siguiendo</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuario:signup' %}"><i class="fas fa-user-plus"></i>  Regístrate</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Inicia sesión</a>
                </li>
                {% endif %}
            </ul>
            <form action="{% url 'blogs:buscar_blogs' %}" method="get" class="form-inline my-2 my-lg-0">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name='texto_busqueda' type="text" placeholder="Buscar por título">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
        </div>
    </nav>

    {% if messages %}
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {% for message in messages %}
        <strong>{{ message }}</strong>
        {% endfor %}
    </div>
    {% endif %}

    {% block content %}{% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/b3d91b3013.js" crossorigin="anonymous"></script>

</body>

</html>

apps/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}

{% block content %}

<main>
    <div class="container col-md-10">
        <div style="padding-top:50px; text-align:center;">
            <h1>Web Playground</h1>
            <p class="lead">CBV, autenticación, registros, perfiles y más</p>
        </div>
    </div>
</main>

{% endblock %}